"""models

Revision ID: 5020c87f3d69
Revises: 
Create Date: 2023-08-05 14:51:34.769098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5020c87f3d69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botcommands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('botservers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_name', sa.String(), nullable=True),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('discord_icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_global_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_avatar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('authorization_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servercommands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('command_name', sa.String(), nullable=True),
    sa.Column('command_description', sa.String(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('discord_name', sa.String(), nullable=True),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['command_description'], ['botcommands.description'], name=op.f('fk_servercommands_command_description_botcommands')),
    sa.ForeignKeyConstraint(['command_id'], ['botcommands.id'], name=op.f('fk_servercommands_command_id_botcommands')),
    sa.ForeignKeyConstraint(['command_name'], ['botcommands.name'], name=op.f('fk_servercommands_command_name_botcommands')),
    sa.ForeignKeyConstraint(['discord_id'], ['botservers.discord_id'], name=op.f('fk_servercommands_discord_id_botservers')),
    sa.ForeignKeyConstraint(['discord_name'], ['botservers.discord_name'], name=op.f('fk_servercommands_discord_name_botservers')),
    sa.ForeignKeyConstraint(['server_id'], ['botservers.id'], name=op.f('fk_servercommands_server_id_botservers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionservers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_name', sa.String(), nullable=True),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('discord_icon', sa.String(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('session_user_id', sa.Integer(), nullable=True),
    sa.Column('session_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessionusers.id'], name=op.f('fk_sessionservers_session_id_sessionusers')),
    sa.ForeignKeyConstraint(['session_user_id'], ['sessionusers.user_id'], name=op.f('fk_sessionservers_session_user_id_sessionusers')),
    sa.ForeignKeyConstraint(['session_username'], ['sessionusers.user_global_name'], name=op.f('fk_sessionservers_session_username_sessionusers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionservers')
    op.drop_table('servercommands')
    op.drop_table('sessionusers')
    op.drop_table('botservers')
    op.drop_table('botcommands')
    # ### end Alembic commands ###
