"""Update models

Revision ID: 8055e81feb7b
Revises: 897f97a58c1d
Create Date: 2023-08-06 03:30:38.316861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8055e81feb7b'
down_revision = '897f97a58c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servercommands', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_servercommands_discord_id_botservers', type_='foreignkey')
        batch_op.drop_constraint('fk_servercommands_command_name_botcommands', type_='foreignkey')
        batch_op.drop_constraint('fk_servercommands_discord_name_botservers', type_='foreignkey')
        batch_op.drop_constraint('fk_servercommands_command_description_botcommands', type_='foreignkey')
        batch_op.drop_column('command_name')
        batch_op.drop_column('command_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servercommands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('command_name', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_servercommands_command_description_botcommands', 'botcommands', ['command_description'], ['description'])
        batch_op.create_foreign_key('fk_servercommands_discord_name_botservers', 'botservers', ['discord_name'], ['discord_name'])
        batch_op.create_foreign_key('fk_servercommands_command_name_botcommands', 'botcommands', ['command_name'], ['name'])
        batch_op.create_foreign_key('fk_servercommands_discord_id_botservers', 'botservers', ['discord_id'], ['discord_id'])
        batch_op.alter_column('server_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
