"""Update BotCommand relationship

Revision ID: f14c48e6d1d1
Revises: 8055e81feb7b
Create Date: 2023-08-08 12:12:16.351328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14c48e6d1d1'
down_revision = '8055e81feb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servercommands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('command_description', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_servercommands_command_description_botcommands'), 'botcommands', ['command_description'], ['description'])
        batch_op.create_foreign_key(batch_op.f('fk_servercommands_command_name_botcommands'), 'botcommands', ['command_name'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servercommands', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_servercommands_command_name_botcommands'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_servercommands_command_description_botcommands'), type_='foreignkey')
        batch_op.drop_column('command_description')
        batch_op.drop_column('command_name')

    # ### end Alembic commands ###
